name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - "provider/**"
      - "schema.yaml"
jobs:
  conventional-commits-pr:
    if: "github.event.pull_request.draft == false && !contains(github.event.head_commit.message, 'chore: apply automatic generated SDK changes')"
    name: Validate Conventional Commits PR
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: catalystsquad/action-validate-conventional-commits-pr@v1
  gen-sdk:
    if: "!contains(github.event.head_commit.message, 'chore: apply automatic generated SDK changes')"
    name: Generate SDKs
    runs-on: ubuntu-latest
    needs:
      - conventional-commits-pr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          ref: ${{ github.ref }}
      - name: Configure git
        uses: fregante/setup-git-user@v1
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Generate provider SDKs
        shell: bash
        run: |
          make generate
      - name: Commit generated SDKs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply automatic generated SDK changes"
