name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
jobs:
  conventional-commits-pr:
    if: "github.event.pull_request.draft == false"
    name: Validate Conventional Commits PR
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: catalystsquad/action-validate-conventional-commits-pr@v1
  test-build:
    name: Test the Build succeeds
    runs-on: ubuntu-latest
    needs:
      - conventional-commits-pr
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Build image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        # tags: ${{ steps.get-tags.outputs.tags }}
        push: false
        cache-from: type=gha,mode=max
        cache-to: type=gha,mode=max
        no-cache: ${{ contains(github.event.head_commit.message, 'no-cache') }}
