name: Semantic Release
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3