name: Image Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "Dockerfile"
jobs:
  release:
    name: Release Image
    runs-on: ubuntu-latest
    outputs:
      new_release_published: "${{ steps.release.outputs.new_release_published }}"
      new_release_version: "${{ steps.release.outputs.new_release_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        # with:
        #   install: true      -
      - name: setup git config
        run: |
          git config --global user.name "Catalyst Squad Automation"
          git config --global user.email "<engineering@catalystsquad.com>"
      - name: Get semver-tags
        run: |
          wget -c https://github.com/catalystsquad/semver-tags/releases/download/v0.3.2/semver-tags.tar.gz -O - | tar -xz
      - name: Semver Tags Run
        id: semver-tags
        run: |
          ./.github/scripts/do-image-release.sh fullrun
      - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/catalystsquad/catalyst-runner-image
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ steps.semver-tags.outputs.New_release_version }}
            type=semver,pattern=${{ steps.semver-tags.outputs.New_release_major.version }}.${{ steps.semver-tags.outputs.New_release_minor.version }}
            type=semver,pattern=${{ steps.semver-tags.outputs.New_release_major.version }}
            type=sha
      - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
        name: Build and push image to Quay
        id: build-push-image
        uses: docker/build-push-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_PAT }}
          DOCKER_REGISTRY_USER: ${{ secrets.QUAY_DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.QUAY_DOCKER_REGISTRY_PASSWORD }}
        with:
          context: .
          file: Dockerfile
          tags: quay.io/catalystsquad/catalyst-runner-image:latest,${{ steps.meta.outputs.tags }}
          push: true
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          no-cache: ${{ contains(github.event.head_commit.message, 'no-cache') }}
